Fix calc site
vattenbagarna/Frontend pull request #149
Opened 2019-05-21 16:20 UTC by Glassinatorn

Closes #145

2019-05-21 16:24 UTC, Glassinatorn commented
**Changed**:
- Fixed hard to soft tabs
- Added new dimensions
- Fixed amount of 0'os in calculations

2019-05-21 20:11 UTC, SpaceLenore requested changes
There are some confusion about certain parts of the code, please review my comments

2019-05-21 20:11 UTC, SpaceLenore commented on calculations.html
> -		<script src="js/APIMiddleware.js"></script>
??? This will probably break stuff???
What about fetching pumps and validating the users token?

2019-05-21 20:11 UTC, SpaceLenore commented on js/calculations/flowCalc.js
> +                    parent = document.getElementById('pump-suggestions');
Please explain what hard coded duplicate lines does.

2019-05-22 10:36 UTC, SpaceLenore requested changes
Some features suddenly missing

2019-05-22 10:36 UTC, SpaceLenore commented on js/calculations/flowCalc.js
> -		document.getElementById("flowSpeed").innerText = roundVel;
suddenly removed features, please resolve

2019-05-22 10:42 UTC, SpaceLenore approved these changes
We are going! :rocket: :satellite: :artificial_satellite:

2019-05-22 10:43 UTC, merged