Added create objects, update objects, home and map.html is integrated with the backend to some extent (products are loaded from the database, the data is saved in the database and the data is loaded from the backend on start
vattenbagarna/Frontend pull request #65
Opened 2019-04-18 21:03 UTC by JohanDjarvKarltorp

closes issues: #48 #49 (#52?)

some file structure were added

2019-04-19 11:32 UTC, eskoglund commented on js/map/popup.js
> +<label>Inner Dimension</label>
Ändra till "Innediamter"

2019-04-19 11:33 UTC, eskoglund commented on js/map/loadLeafletMaterialMap.js
> +    //const jsonLoad = JSON.parse(jsonData)
Ta bort ifall den inte används

2019-04-19 11:37 UTC, eskoglund commented on calculations.html
> +			<a href="home.html">Home</a>
Ändra till "Hem" i texten eftersom vi kör allt annat på svenska

2019-04-19 11:38 UTC, eskoglund commented on home.html
> +			<a class="active" href="home.html">Home</a>
Ändra till "Hem" i texten eftersom vi kör allt annat på svenska

2019-04-19 11:41 UTC, eskoglund commented on js/map/classes.js
> +        // Behövs kommenteras
Ta bort eller kommentera ifall det behövs

2019-04-19 11:42 UTC, eskoglund commented on js/map/loadLeafletMaterialMap.js
> +// Imports Google maps javascript api key from getKey.js file
Kan flyttas ner en rad

2019-04-19 11:43 UTC, eskoglund commented on js/map/loadLeafletMaterialMap.js
> +        //console.log(pixelPosition);
Ta bort ifall den inte används

2019-04-19 11:48 UTC, eskoglund commented on js/products/newObject.js
> +		<input class="newInput" type="text" placeholder="värde">
Tror det ska vara stor bokstav på "värde", samt möjligen "titel" på raden ovanför

2019-04-19 11:49 UTC, eskoglund commented on js/products/updateObject.js
> +		<input class="newInput" type="text" placeholder="värde">
Samma som kommentaren lite längre upp. Ge "värde" och "titel" stor bokstav

2019-04-19 11:50 UTC, eskoglund commented on js/products/updateObject.js
> +            //Modell i framtiden
En svensk kommentar?

2019-04-19 11:53 UTC, eskoglund commented on newObject.html
> +			<a href="home.html">Home</a>
Ändra till "Hem" eftersom vi kör på svenska

2019-04-19 11:54 UTC, eskoglund commented on updateObject.html
> +			<a href="home.html">Home</a>
Ändra till "Hem" eftersom vi kör på svenska

2019-04-19 11:55 UTC, eskoglund commented on updateObject.html
> +				<h1>Updatera Produkt</h1>
Du har missat ett "p" i "Updatera Produkt". Det ska alltså stå "Uppdatera"

2019-04-19 11:56 UTC, eskoglund requested changes
I have made some comments on some small changes I want you to fix

2019-04-21 11:17 UTC, eskoglund approved these changes
Good job!

2019-04-21 20:54 UTC, SpaceLenore requested changes
As you can see by my comments, some js files are not found (404) due to the file structure has changed to use different folders. I found two but haven't had the possibility to look at all script tags. Please fix these two and verify the other script tags.

2019-04-21 20:54 UTC, SpaceLenore commented on materiallist.html
> +	<script type="module" src="js/getKey.js"></script>
`js/getKey.js` is not found since it has been moved to `/map/`

2019-04-21 20:54 UTC, SpaceLenore commented on materiallist.html
> +	<script type="module" src="js/loadLeafletMaterialMap.js"></script>
`js/loadLeafletMap.js` is not found since it has been moved to `/map/`

2019-04-23 13:43 UTC, SpaceLenore approved these changes

2019-04-23 13:45 UTC, merged